### ISSUE TITLE
Refactor discogs_tagger.py

### ISSUE THREAD

**Issue by triplem** [jesseward/discogstagger#16]
This module has slightly outgrown itself. I believe we should do a refactoring, to make future enhancements easier. 

There are a couple of opportunities here:
Make the whole config handling easier -> handle this in its own module and use the parameters from an object, this will also make the setting of default values easier, in that those are not set in the taggerutils.py but in the one configure handling module.
Refactor the track-loop, so that this can be adopted easier then right now. Probably we should define an own object "Track"/"TrackContainer" and define certain properties on this one.
Refactor the source directory determination to allow for batch calls (e.g. my source dir is ~/Music and in there are several sub-directories which contain audio files). Up until now the source dir has to contain (except multi-disc releases) audio files.

**Comment by jesseward** [comment]
closing this old ticket, as work to separate and refactor the configuration data was completed in v3.0.0
