### ISSUE TITLE
Set Tags from specific file (id.txt) manually

### ISSUE THREAD

**Issue by triplem** [jesseward/discogstagger#18]
Right now we are just using the discogs_id from the id.txt and set this in the Tags of the audio files. Allow for other tags as well. 

In a first step I am thinking about the "encoder" field, but similar all other fields (even those fetched from discogs), could be set in the id.txt.

**Comment by jesseward** [comment]
this repo is quite stale and I won't add this feature. Closing this request as a won't fix.
