### ISSUE TITLE
Make Tags multi-value aware

### ISSUE THREAD

**Issue by triplem** [jesseward/discogstagger#19]
Right now, we can split multiple values in tags with a configurable value (e.g. \\). This makes it possible to split these tags into multi value fields by e.g. puddletag. This should be done directly from discogstagger.

Since we are using mediafile.py from the beets-project this depends on the issue #119 in there repository:

https://github.com/sampsyo/beets/issues/119

**Comment by jesseward** [comment]
this repo is quite stale and I won't add this feature. Closing this request as a won't fix.
