### ISSUE TITLE
Images won't download

### ISSUE THREAD

**Issue by fwolfers** [jesseward/discogstagger#25]
Hey. i'm getting this error while fetching infos from discogs.

ERROR:discogstagger.taggerutils:Unable to download image '', skipping. Error: Unsupported URL  ().

**Comment by jesseward** [comment]
hey @fwolfers , please pass along the release id you're attempting to tag.

**Comment by jesseward** [comment]
@fwolfers , thanks for reporting this. I have a fix locally for this and will be checking it in this week,

**Comment by jesseward** [comment]
Addressed in commit https://github.com/jesseward/discogstagger/commit/7cd13695d818fbc2b9f4cd2bee9de8e5442acff0
